model: "Unet"
dataset: "Freiburg Forest"
transform: train_transform
train_ratio: 0.85
validation_ratio: 0.05
test_ratio: 0.10
batch_size: 5
epochs: 2
loss: "Cross Entropy"
optimizer: "Adam"
lr: 0.001
scheduler: None
scheduler_params: None
height: 256
width: 256
model_name: None  # *.pt file to save